#!/bin/sh

# Script that runs the assembly judge inside a container.
# 
#   - stdin: run configuration (JSON)
#   - stdout: evaluation results (JSON)
#   - stderr: should be empty
#   - exit status: should be zero

DIR="$(dirname $0)"

ulimit -n -S 1024
ulimit -n 4096
python "$DIR/assembly_judge.py"
